license = "BSD3"
with_readme = true
website = "https://reconfigure.io/" # {{ project }}

[files]
directories = ["src", "verilog", "teak", "optim"]
templates = [".gitignore", "src/{{ project }}.go", "optim/default.rules", "Makefile"]

[config]
version = "0.1.0"
version_control = "git"

[[user]]
license_file = "LICENSE"
