license = "BSD3"
with_readme = true

[files]
files = []
directories = ["{{ Project }}"]
templates = ["{{ Project }}/Lib.idr","{{ Project }}.idr","{{ project }}.ipkg",".gitignore", "Makefile"]

[config]
version = "0.1.0"
version_control = "git"
