license = "BSD3"
with_readme = true
website = "https://hackage.haskell.org/package/" # {{ project }}

[files]
files = []
directories = ["src","app"]
templates = ["src/Lib.hs","app/Main.hs","Setup.hs",
    "{{ project }}.cabal", "stack.yaml",
    ".travis.yml", ".gitignore"]

[config]
version = "0.1.0.0"
version_control = "git"

[[user]]
license_file = "LICENSE"
