language: julia
os:
  - osx
  - linux
julia:
  - 0.4
  - 0.5
  - nightly
# change this is the email notifications annoy you
# notifications:
#   email: false
after_success:
  - julia -e 'cd(Pkg.dir("{{ Project }}")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
